MAIN_CATEGORY = {
    "TABLESPACE_CATEGORY": "TABLESPACE",
    "MEMORY_CATEGORY" : "MEMORY",
    "ALERT_LOGS_CATEGORY" : "ALERT LOGS",
    "VIEW_REPORT" : "VIEW DAILY REPORT",
    "SELECT DB" : "BACK TO DB LIST"
}

TABLESPACE_CATEGORY = {
    "TABLESPACE_USAGE" : "TABLESPACE USAGE",
    "TABLESPACE_TREND" : "TABLESPACE USAGE TREND",
    "MAIN_CATEGORY" : "BACK TO MAIN MENU"
}

MEMORY_CATEGORY = {
    "SGAOPER" : "SGA OPERATION",
    "PGAUSAGE" : "PGA USAGE",
    "MAIN_CATEGORY" : "BACK TO MAIN MENU"
}

ALERT_LOGS_CATEGORY = {
    "STARTDATE" : "SET START DATE",
    "ENDDATE" :"SET END DATE",
    "VIEWLOG" : "VIEW LOGS",
    "MAIN_CATEGORY" : "BACK TO MAIN MENU"
}

