# Excel Header Define

DBINFO_COMMON_HEADER = ["DB UNIQUE NAME", "DATABASE_TYPE", "VERSION", "DIAGDATE"]
DBINFO_INSTANCE_HEADER = ["INSTANCE_NUMBER","INSTANCE_NAME", "HOSTNAME"]
MEMORY_HEADER = ["INSTANCE_NUMBER", "SGA","PGA", "ALLOCATE", "USED", "FREEABLE", "PGALIMIT","USED PCT"]
SGA_OPERATION_HEADER = ["INSTANCE_NUMBER", "COMPONENT","START_TIME","END_TIME","OPERATION", "OPERATION_TYPE","INITIAL","TARGET","FINAL","STATUS"]
DATA_GUARD_HEADER = ["INSTANCE_NUMBER", "DB UNIQ NAME","PARENT DB UNIQ NAME","DATABASE ROLE","CURRENT SCN","DELAY"]
ASM_HEADER = ["DISKGROUP", "TOTAL", "USABLE", "REDUNDANCY", "USED %", "WARNING"]
TABLESPACE_HEADER = ["TABLESPACE_NAME", "TOTAL MB", "USED MB", "USED %", "WARNING"]
ALERT_HEADER = ["INSTANCE_NUMBER","DATE","MESSAGE"]
